// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkBase.Infrastructure.Persistence;

#nullable disable

namespace WorkBase.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkBaseDbContext))]
    [Migration("20260326152822_AddTimeTrackingTables")]
    partial class AddTimeTrackingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.DataScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomFilter")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_filter");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("ScopeLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope_level");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_iam_data_scopes");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_iam_data_scopes_tenant_id");

                    b.HasIndex("RoleId", "Module")
                        .IsUnique()
                        .HasDatabaseName("ix_iam_data_scopes_role_id_module");

                    b.ToTable("iam_data_scopes", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at");

                    b.Property<string>("EnabledBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("enabled_by");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_iam_feature_flags");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_iam_feature_flags_tenant_id");

                    b.HasIndex("TenantId", "Module")
                        .IsUnique()
                        .HasDatabaseName("ix_iam_feature_flags_tenant_id_module");

                    b.ToTable("iam_feature_flags", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module");

                    b.Property<string>("Scope")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_iam_permissions");

                    b.HasIndex("Module", "Action", "Scope")
                        .IsUnique()
                        .HasDatabaseName("ix_iam_permissions_module_action_scope");

                    b.ToTable("iam_permissions", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("level");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_iam_roles");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_iam_roles_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_iam_roles_tenant_id_name");

                    b.ToTable("iam_roles", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_iam_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_iam_role_permissions_permission_id");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_iam_role_permissions_role_id_permission_id");

                    b.ToTable("iam_role_permissions", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("keycloak_id");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_iam_users");

                    b.HasIndex("KeycloakId")
                        .IsUnique()
                        .HasDatabaseName("ix_iam_users_keycloak_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_iam_users_tenant_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_iam_users_tenant_id_email");

                    b.ToTable("iam_users", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_iam_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_iam_user_roles_role_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_iam_user_roles_tenant_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_iam_user_roles_user_id_role_id");

                    b.ToTable("iam_user_roles", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("termination_date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_org_employees");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_org_employees_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_org_employees_user_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_org_employees_tenant_id_email");

                    b.HasIndex("TenantId", "EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_org_employees_tenant_id_employee_number")
                        .HasFilter("employee_number IS NOT NULL");

                    b.ToTable("org_employees", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.EmployeeAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_org_employee_assignments");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_org_employee_assignments_employee_id");

                    b.HasIndex("OrganizationUnitId")
                        .HasDatabaseName("ix_org_employee_assignments_organization_unit_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_org_employee_assignments_position_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_org_employee_assignments_tenant_id");

                    b.ToTable("org_employee_assignments", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.OrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_org_units");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_org_units_parent_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_org_units_tenant_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_org_units_type_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_org_units_tenant_id_code")
                        .HasFilter("code IS NOT NULL");

                    b.ToTable("org_units", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.OrganizationUnitClosure", b =>
                {
                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ancestor_id");

                    b.Property<Guid>("DescendantId")
                        .HasColumnType("uuid")
                        .HasColumnName("descendant_id");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.HasKey("AncestorId", "DescendantId")
                        .HasName("pk_org_unit_closure");

                    b.HasIndex("AncestorId")
                        .HasDatabaseName("ix_org_unit_closure_ancestor_id");

                    b.HasIndex("DescendantId")
                        .HasDatabaseName("ix_org_unit_closure_descendant_id");

                    b.ToTable("org_unit_closure", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.OrganizationUnitType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_org_unit_types");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_org_unit_types_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_org_unit_types_tenant_id_name");

                    b.ToTable("org_unit_types", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_org_positions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_org_positions_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_org_positions_tenant_id_name");

                    b.ToTable("org_positions", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.SupervisorRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid>("SubordinateEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("subordinate_employee_id");

                    b.Property<Guid>("SupervisorEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("supervisor_employee_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_org_supervisor_relations");

                    b.HasIndex("SubordinateEmployeeId")
                        .HasDatabaseName("ix_org_supervisor_relations_subordinate_employee_id");

                    b.HasIndex("SupervisorEmployeeId")
                        .HasDatabaseName("ix_org_supervisor_relations_supervisor_employee_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_org_supervisor_relations_tenant_id");

                    b.HasIndex("TenantId", "SubordinateEmployeeId", "EndDate")
                        .HasDatabaseName("ix_org_supervisor_relations_tenant_id_subordinate_employee_id_");

                    b.ToTable("org_supervisor_relations", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_org_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_org_tenants_slug");

                    b.ToTable("org_tenants", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.TimeTracking.Domain.Entities.QrToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("LocationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("location_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by_employee_id");

                    b.HasKey("Id")
                        .HasName("pk_time_qr_tokens");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_time_qr_tokens_tenant_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_time_qr_tokens_token");

                    b.HasIndex("TenantId", "ExpiresAt")
                        .HasDatabaseName("ix_time_qr_tokens_tenant_id_expires_at");

                    b.ToTable("time_qr_tokens", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.TimeTracking.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<TimeOnly>("PlannedEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("planned_end");

                    b.Property<TimeOnly>("PlannedStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("planned_start");

                    b.Property<string>("ShiftType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("shift_type");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_time_schedules");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_time_schedules_template_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_time_schedules_tenant_id");

                    b.HasIndex("EmployeeId", "Date")
                        .HasDatabaseName("ix_time_schedules_employee_id_date");

                    b.HasIndex("TenantId", "EmployeeId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_time_schedules_tenant_id_employee_id_date");

                    b.ToTable("time_schedules", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.TimeTracking.Domain.Entities.ScheduleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_time_schedule_templates");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_time_schedule_templates_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_time_schedule_templates_tenant_id_name");

                    b.ToTable("time_schedule_templates", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.TimeTracking.Domain.Entities.TimeAnomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TimeSheetId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_sheet_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_time_anomalies");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_time_anomalies_tenant_id");

                    b.HasIndex("TimeSheetId")
                        .HasDatabaseName("ix_time_anomalies_time_sheet_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_time_anomalies_tenant_id_status");

                    b.HasIndex("TenantId", "EmployeeId", "Date")
                        .HasDatabaseName("ix_time_anomalies_tenant_id_employee_id_date");

                    b.ToTable("time_anomalies", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.TimeTracking.Domain.Entities.TimeCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrectedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("corrected_by");

                    b.Property<DateTime>("CorrectedClockIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("corrected_clock_in");

                    b.Property<DateTime>("CorrectedClockOut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("corrected_clock_out");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("OriginalClockIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_clock_in");

                    b.Property<DateTime>("OriginalClockOut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_clock_out");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TimeSheetId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_sheet_id");

                    b.HasKey("Id")
                        .HasName("pk_time_corrections");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_time_corrections_tenant_id");

                    b.HasIndex("TimeSheetId")
                        .HasDatabaseName("ix_time_corrections_time_sheet_id");

                    b.HasIndex("TenantId", "EmployeeId", "Date")
                        .HasDatabaseName("ix_time_corrections_tenant_id_employee_id_date");

                    b.ToTable("time_corrections", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.TimeTracking.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_time");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("method");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("note");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_time_entries");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_time_entries_tenant_id");

                    b.HasIndex("EmployeeId", "EntryTime")
                        .HasDatabaseName("ix_time_entries_employee_id_entry_time");

                    b.HasIndex("TenantId", "EmployeeId", "EntryTime")
                        .HasDatabaseName("ix_time_entries_tenant_id_employee_id_entry_time");

                    b.ToTable("time_entries", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.TimeTracking.Domain.Entities.TimeSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<TimeSpan>("NetWorked")
                        .HasColumnType("interval")
                        .HasColumnName("net_worked");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<TimeSpan>("TotalBreaks")
                        .HasColumnType("interval")
                        .HasColumnName("total_breaks");

                    b.Property<TimeSpan>("TotalWorked")
                        .HasColumnType("interval")
                        .HasColumnName("total_worked");

                    b.HasKey("Id")
                        .HasName("pk_time_sheets");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_time_sheets_tenant_id");

                    b.HasIndex("EmployeeId", "Date")
                        .HasDatabaseName("ix_time_sheets_employee_id_date");

                    b.HasIndex("TenantId", "EmployeeId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_time_sheets_tenant_id_employee_id_date");

                    b.ToTable("time_sheets", (string)null);
                });

            modelBuilder.Entity("WorkBase.Shared.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<string>("ChangedColumns")
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_columns");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_audit_entries_entity_type");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audit_entries_tenant_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_entries_timestamp");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entries_entity_type_entity_id");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.DataScope", b =>
                {
                    b.HasOne("WorkBase.Modules.Identity.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iam_data_scopes_role_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("WorkBase.Modules.Identity.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iam_role_permissions_iam_permissions_permission_id");

                    b.HasOne("WorkBase.Modules.Identity.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iam_role_permissions_iam_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("WorkBase.Modules.Identity.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iam_user_roles_iam_roles_role_id");

                    b.HasOne("WorkBase.Modules.Identity.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iam_user_roles_iam_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.EmployeeAssignment", b =>
                {
                    b.HasOne("WorkBase.Modules.Organization.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_employee_assignments_employee_employee_id");

                    b.HasOne("WorkBase.Modules.Organization.Domain.Entities.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_employee_assignments_organization_unit_organization_uni");

                    b.HasOne("WorkBase.Modules.Organization.Domain.Entities.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_employee_assignments_position_position_id");
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.OrganizationUnit", b =>
                {
                    b.HasOne("WorkBase.Modules.Organization.Domain.Entities.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_org_units_org_units_parent_id");

                    b.HasOne("WorkBase.Modules.Organization.Domain.Entities.OrganizationUnitType", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_units_organization_unit_type_type_id");
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.OrganizationUnitClosure", b =>
                {
                    b.HasOne("WorkBase.Modules.Organization.Domain.Entities.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_unit_closure_organization_unit_ancestor_id");

                    b.HasOne("WorkBase.Modules.Organization.Domain.Entities.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_unit_closure_organization_unit_descendant_id");
                });

            modelBuilder.Entity("WorkBase.Modules.Organization.Domain.Entities.SupervisorRelation", b =>
                {
                    b.HasOne("WorkBase.Modules.Organization.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("SubordinateEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_supervisor_relations_org_employees_subordinate_employee");

                    b.HasOne("WorkBase.Modules.Organization.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("SupervisorEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_supervisor_relations_org_employees_supervisor_employee_");
                });

            modelBuilder.Entity("WorkBase.Modules.TimeTracking.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("WorkBase.Modules.TimeTracking.Domain.Entities.ScheduleTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_time_schedules_schedule_template_template_id");
                });

            modelBuilder.Entity("WorkBase.Modules.TimeTracking.Domain.Entities.TimeAnomaly", b =>
                {
                    b.HasOne("WorkBase.Modules.TimeTracking.Domain.Entities.TimeSheet", null)
                        .WithMany()
                        .HasForeignKey("TimeSheetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_time_anomalies_time_sheet_time_sheet_id");
                });

            modelBuilder.Entity("WorkBase.Modules.TimeTracking.Domain.Entities.TimeCorrection", b =>
                {
                    b.HasOne("WorkBase.Modules.TimeTracking.Domain.Entities.TimeSheet", null)
                        .WithMany()
                        .HasForeignKey("TimeSheetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_time_corrections_time_sheet_time_sheet_id");
                });

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("WorkBase.Modules.Identity.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
